### ISSUE TITLE
CPA increases the replicas

### ISSUE THREAD

**Issue by mortyre** [jthomperoo/custom-pod-autoscaler#124] opened 2020-11-27 18:05 UTC
**Describe the bug**
during the update my Deployment the CPA increases the replicas

**To Reproduce**
1. My Deployment with replicas 50. CPA sees that and does nothing

> I1127 17:46:24.740505       1 autoscaler.go:55] Attempting to get resource metrics
> I1127 17:46:24.740522       1 metric.go:76] Gathering metrics in per-resource mode
> I1127 17:46:24.740761       1 metric.go:94] Attempting to run metric gathering logic
> I1127 17:46:25.521068       1 metric.go:105] Metrics gathered: {"busy": 0, "ready": 50, "initializing": 0, "available": 50, "busy_containers": 0.0}
> I1127 17:46:25.521100       1 autoscaler.go:63] Retrieved metrics: [0xc000352100]
> I1127 17:46:25.521109       1 autoscaler.go:65] Attempting to evaluate metrics
> I1127 17:46:25.521117       1 evaluate.go:61] Evaluating gathered metrics
> I1127 17:46:25.521316       1 evaluate.go:78] Attempting to run evaluation logic
> I1127 17:46:25.554694       1 evaluate.go:83] Evaluation determined: {"targetReplicas": 48}
> I1127 17:46:25.554733       1 evaluate.go:85] Attempting to parse evaluation
> I1127 17:46:25.554775       1 evaluate.go:91] Evaluation parsed: &{TargetReplicas:48}
> I1127 17:46:25.554800       1 autoscaler.go:74] Metrics evaluated: &{TargetReplicas:48}
> I1127 17:46:25.554815       1 autoscaler.go:76] Attempting to scale resource based on evaluation
> I1127 17:46:25.554855       1 scale.go:82] Replica count determined: 50
> I1127 17:46:25.554888       1 scale.go:86] Scale target less than min at 50 replicas, setting target to min 50 replicas
> I1127 17:46:25.555178       1 scale.go:145] Picked max evaluation over stabilization window of 600 seconds; replicas 50
> I1127 17:46:25.555190       1 scale.go:181] No change in target replicas, maintaining 50 replicas
> I1127 17:46:25.555195       1 autoscaler.go:89] Scaled resource successfully

2. When I updated my deployment CPA is trying to increase the number of replicas

> I1127 17:47:25.505861       1 autoscaler.go:65] Attempting to evaluate metrics
> I1127 17:47:25.505877       1 evaluate.go:61] Evaluating gathered metrics
> I1127 17:47:25.506240       1 evaluate.go:78] Attempting to run evaluation logic
> I1127 17:47:25.547133       1 evaluate.go:83] Evaluation determined: {"targetReplicas": 61}
> I1127 17:47:25.547157       1 evaluate.go:85] Attempting to parse evaluation
> I1127 17:47:25.547189       1 evaluate.go:91] Evaluation parsed: &{TargetReplicas:61}
> I1127 17:47:25.547209       1 autoscaler.go:74] Metrics evaluated: &{TargetReplicas:61}
> I1127 17:47:25.547217       1 autoscaler.go:76] Attempting to scale resource based on evaluation
> I1127 17:47:25.547244       1 scale.go:82] Replica count determined: 50
> I1127 17:47:25.547262       1 scale.go:92] Scale target set to 50 replicas
> I1127 17:47:25.547492       1 scale.go:145] Picked max evaluation over stabilization window of 600 seconds; replicas 61
> I1127 17:47:25.547505       1 scale.go:152] Rescaling from 50 to 61 replicas
> I1127 17:47:25.547511       1 scale.go:153] Attempting to parse group version
> I1127 17:47:25.547519       1 scale.go:159] Group version parsed: apps/v1
> I1127 17:47:25.547528       1 scale.go:166] Attempting to get scale subresource for managed resource

**Expected behavior**
I expect an update without increase replicas. Logic of my evaluate.py simple - add 2 pods and remove 1 for autoscaling

**Kubernetes Details (`kubectl version`):**
Kubernetes version - 1.15
 kubectl version 1.15
CPA - 1.0.1

**Additional context**
Why is this happening? I do not have enough resources in the cluster for these replicas.

**Comment by jthomperoo** [comment] 2020-11-27 18:27
Thanks for the bug report.

So just to clarify for me, you have a running CPA that is targeting 50 replicas, then you update the deployment and suddenly the CPA is targeting 61 replicas? 

I see from the first log trace you have this:

```
I1127 17:46:25.521068 1 metric.go:105] Metrics gathered: {"busy": 0, "ready": 50, "initializing": 0, "available": 50, "busy_containers": 0.0}
```

So I assume your evaluation logic is using this, are these metrics gathered different after you update? Just as I can't see the metrics gathered in the second log trace.

Hopefully we can get this fixed for you quickly!

**Comment by mortyre** [comment] 2020-11-27 19:15
> So just to clarify for me, you have a running CPA that is targeting 50 replicas, then you update the deployment and suddenly the CPA is targeting 61 replicas?

Yes, it's right

> So I assume your evaluation logic is using this, are these metrics gathered different after you update? Just as I can't see the metrics gathered in the second log trace.

Yes, my metrics.py gathered this metrics from Prometheus and use this formula for scale up and down
`busy / (busy + ready) * 100`
if greater 80 than scale up 2 pods

Sorry for interrpted logs, this full:

> I1127 19:02:24.739487       1 autoscaler.go:55] Attempting to get resource metrics
> I1127 19:02:24.739496       1 metric.go:76] Gathering metrics in per-resource mode
> I1127 19:02:24.739713       1 metric.go:94] Attempting to run metric gathering logic
> I1127 19:02:25.554806       1 metric.go:105] Metrics gathered: {"busy": 1, "ready": 46, "initializing": 1, "available": 47, "busy_containers": 2.127659574468085}
> I1127 19:02:25.554828       1 autoscaler.go:63] Retrieved metrics: [0xc0002d9700]
> I1127 19:02:25.554838       1 autoscaler.go:65] Attempting to evaluate metrics
> I1127 19:02:25.554844       1 evaluate.go:61] Evaluating gathered metrics
> I1127 19:02:25.555032       1 evaluate.go:78] Attempting to run evaluation logic
> I1127 19:02:25.589468       1 evaluate.go:83] Evaluation determined: {"targetReplicas": 61}
> I1127 19:02:25.589494       1 evaluate.go:85] Attempting to parse evaluation
> I1127 19:02:25.589521       1 evaluate.go:91] Evaluation parsed: &{TargetReplicas:61}
> I1127 19:02:25.589535       1 autoscaler.go:74] Metrics evaluated: &{TargetReplicas:61}
> I1127 19:02:25.589541       1 autoscaler.go:76] Attempting to scale resource based on evaluation
> I1127 19:02:25.589550       1 scale.go:73] Determining replica count for resource 'war-prod-gps'
> I1127 19:02:25.589556       1 scale.go:82] Replica count determined: 50
> I1127 19:02:25.589569       1 scale.go:92] Scale target set to 50 replicas
> I1127 19:02:25.589824       1 scale.go:145] Picked max evaluation over stabilization window of 600 seconds; replicas 61
> I1127 19:02:25.589837       1 scale.go:152] Rescaling from 50 to 61 replicas
> I1127 19:02:25.589843       1 scale.go:153] Attempting to parse group version
> I1127 19:02:25.589851       1 scale.go:159] Group version parsed: apps/v1
> I1127 19:02:25.589860       1 scale.go:166] Attempting to get scale subresource for managed resource
> I1127 19:02:25.592332       1 scale.go:171] Scale subresource retrieved: &Scale{ObjectMeta:{war-prod-gps  war-prod /apis/apps/v1/namespaces/war-prod/deployments/war-prod-gps/scale 1380c71a-66ac-4681-98d2-3354c08c143d 12513762 0 2020-11-24 12:33:01 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:ScaleSpec{Replicas:50,},Status:ScaleStatus{Replicas:63,Selector:name=war-prod-gps,},}
> I1127 19:02:25.592401       1 scale.go:173] Attempting to apply scaling changes to resource
> I1127 19:02:25.639037       1 scale.go:179] Application of scale successful

Ready 46 of 50 because Kubernetes sent SIGTERM to my pods and they shutdown

**Comment by jthomperoo** [comment] 2020-11-27 19:59
Presumably in your metric gathering stage you calculate that `busy_containers` value.

In your evaluation stage you want it so that if `busy_containers` is > 80% you want it to add 2 replicas to your deployment, if it is less than some threshold you want to take 1 replica away from the deployment?

So the expected behaviour for the second one is:

```
{"busy": 1, "ready": 46, "initializing": 1, "available": 47, "busy_containers": 2.127659574468085}

busy / (busy + ready) * 100

1 / (1 + 46) * 100 = 2.127659574
```

Since `2.127659574 < 80` it should not add two replicas to the deployment.

Would you be willing to share your evaluation stage just so I can help try to work out what's happening?

**Comment by mortyre** [comment] 2020-11-28 19:38
No, I don't have any problem with my metrics.py and evaluate.py. This work fine.
Example, step by step:
I have deployment is 50 replicas
```
$ k get deploy war-prod-gps
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
war-prod-gps   50/50   50           50          4d6h
```

CPA log is fine (50 is minimum replicas)
```
I1128 19:15:34.674183       1 autoscaler.go:55] Attempting to get resource metrics
I1128 19:15:34.674199       1 metric.go:76] Gathering metrics in per-resource mode
I1128 19:15:34.674572       1 metric.go:94] Attempting to run metric gathering logic
I1128 19:15:35.470779       1 metric.go:105] Metrics gathered: {"busy": 0, "ready": 50, "initializing": 0, "available": 50, "busy_containers": 0.0}
I1128 19:15:35.470798       1 autoscaler.go:63] Retrieved metrics: [0xc0007d8ac0]
I1128 19:15:35.470807       1 autoscaler.go:65] Attempting to evaluate metrics
I1128 19:15:35.470814       1 evaluate.go:61] Evaluating gathered metrics
I1128 19:15:35.470993       1 evaluate.go:78] Attempting to run evaluation logic
I1128 19:15:35.504204       1 evaluate.go:83] Evaluation determined: {"targetReplicas": 48}
I1128 19:15:35.504221       1 evaluate.go:85] Attempting to parse evaluation
I1128 19:15:35.504258       1 evaluate.go:91] Evaluation parsed: &{TargetReplicas:48}
I1128 19:15:35.504269       1 autoscaler.go:74] Metrics evaluated: &{TargetReplicas:48}
I1128 19:15:35.504275       1 autoscaler.go:76] Attempting to scale resource based on evaluation
I1128 19:15:35.504284       1 scale.go:73] Determining replica count for resource 'war-prod-gps'
I1128 19:15:35.504290       1 scale.go:82] Replica count determined: 50
I1128 19:15:35.504301       1 scale.go:86] Scale target less than min at 50 replicas, setting target to min 50 replicas
I1128 19:15:35.504519       1 scale.go:145] Picked max evaluation over stabilization window of 600 seconds; replicas 50
I1128 19:15:35.504534       1 scale.go:181] No change in target replicas, maintaining 50 replicas
I1128 19:15:35.504539       1 autoscaler.go:89] Scaled resource successfully
```
After that I update image for my deployment
```
$ k set image  deployment war-prod-gps war-gameplay=war-gps:v2
deployment.apps/war-prod-gps image updated
```
```
$ k get deploy war-prod-gps -w
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
war-prod-gps   45/50   18           45          4d6h
war-prod-gps   45/61   18           45          4d6h
....
war-prod-gps   60/61   22           60          4d6h
war-prod-gps   61/61    22           61          4d6h
```
 And in CPA log
```
I1128 19:28:34.675489       1 autoscaler.go:55] Attempting to get resource metrics
I1128 19:28:34.675505       1 metric.go:76] Gathering metrics in per-resource mode
I1128 19:28:34.675766       1 metric.go:94] Attempting to run metric gathering logic
I1128 19:28:35.477275       1 metric.go:105] Metrics gathered: {"busy": 1, "ready": 46, "initializing": 0, "available": 47, "busy_containers": 2.127659574468085}
I1128 19:28:35.477302       1 autoscaler.go:63] Retrieved metrics: [0xc000198060]
I1128 19:28:35.477320       1 autoscaler.go:65] Attempting to evaluate metrics
I1128 19:28:35.477329       1 evaluate.go:61] Evaluating gathered metrics
I1128 19:28:35.477623       1 evaluate.go:78] Attempting to run evaluation logic
I1128 19:28:35.512979       1 evaluate.go:83] Evaluation determined: {"targetReplicas": 61}
I1128 19:28:35.513012       1 evaluate.go:85] Attempting to parse evaluation
I1128 19:28:35.513056       1 evaluate.go:91] Evaluation parsed: &{TargetReplicas:61}
I1128 19:28:35.513091       1 autoscaler.go:74] Metrics evaluated: &{TargetReplicas:61}
I1128 19:28:35.513109       1 autoscaler.go:76] Attempting to scale resource based on evaluation
I1128 19:28:35.513125       1 scale.go:73] Determining replica count for resource 'war-prod-gps'
I1128 19:28:35.513138       1 scale.go:82] Replica count determined: 50
I1128 19:28:35.513167       1 scale.go:92] Scale target set to 50 replicas
I1128 19:28:35.513544       1 scale.go:145] Picked max evaluation over stabilization window of 600 seconds; replicas 61
I1128 19:28:35.513563       1 scale.go:152] Rescaling from 50 to 61 replicas
I1128 19:28:35.513576       1 scale.go:153] Attempting to parse group version
I1128 19:28:35.513591       1 scale.go:159] Group version parsed: apps/v1
I1128 19:28:35.513614       1 scale.go:166] Attempting to get scale subresource for managed resource
I1128 19:28:35.516817       1 scale.go:171] Scale subresource retrieved: &Scale{ObjectMeta:{war-prod-gps  war-prod /apis/apps/v1/namespaces/war-prod/deployments/war-prod-gps/scale 1380c71a-66ac-4681-98d2-3354c08c143d 12866262 0 2020-11-24 12:33:01 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:ScaleSpec{Replicas:50,},Status:ScaleStatus{Replicas:63,Selector:name=war-prod-gps,},}
I1128 19:28:35.516908       1 scale.go:173] Attempting to apply scaling changes to resource
I1128 19:28:35.618983       1 scale.go:179] Application of scale successful
I1128 19:28:35.619001       1 autoscaler.go:89] Scaled resource successfully
```

The problem is CPA set TargetReplicas:61 and Rescaling from 50 to 61 replicas

**Comment by jthomperoo** [comment] 2020-11-29 22:14
Hi, sorry I seem to still be confused on the issue here. Let me outline the process and just tell me where I am going wrong.

For the first instance:

1. Deployment is at 50 replicas
2. Metric gathering stage runs, it generates this:
```json
{"busy": 0, "ready": 50, "initializing": 0, "available": 50, "busy_containers": 0.0}
````
3. The JSON generated by the metric gathering is then fed into the evaluation stage, which returns this:
```json
{"targetReplicas": 48}
```
4. The CPA then reads this `targetReplicas` value and scales using the configuration, the minimum number of replicas is set to `50` so it scales to `50`.
5. This is all accurate and expected.

For the second instance, after updating the deployment image:

1. Deployment is at 50 replicas
2. Metric gathering stage runs, it generates this:
```json
{"busy": 1, "ready": 46, "initializing": 0, "available": 47, "busy_containers": 2.127659574468085}
````
3. The JSON generated by the metric gathering is then fed into the evaluation stage, which returns this:
```json
{"targetReplicas": 61}
```
4. The CPA then reads this `targetReplicas` value and scales to it, setting the target replicas of the deployment to `61`
5. This is unexpected, it should not scale to `61`

It seems to me that the issue is that the evaluation stage is reporting `61` target replicas, the CPA is correctly reading this value and scaling to it. If the deployment should not be scaled to `61` replicas, then the evaluation stage should not report back `61` target replicas in its JSON response.

**Comment by mortyre** [comment] 2020-11-30 10:17
You were right! Problem in my avaluate.py not in CPA 
I used simple code from example to get current replicas:
 https://github.com/jthomperoo/custom-pod-autoscaler/blob/master/example/simple-pod-metrics-python/evaluate.py#L53

But `["status"]["replicas"]` is old replica set + new replica set. When I update my deployment the old RS decrease from 50 to 44 and the new RS set 17 then status of Deployment 61. 
`target_replica_count = int(spec["resource"]["status"]["replicas"])` is 61
I change to `target_replica_count = int(spec["resource"]["spec"]["replicas"])` and my problem is gone

Maybe it is necessary to change in your example too?
Anyway, thanks a lot for the help

**Comment by jthomperoo** [comment] 2020-12-01 16:17
Great, glad to hear that's working now.

Good catch with that example, I'll update that to the behaviour you've outlined there as that could be confusing. I'll close this issue once I merge in the changes to that example.

Thanks!

**Closed** 2020-12-01 22:41 UTC
